### ISSUE TITLE
Customizable links/paths between nodes

### ISSUE THREAD

**Issue by aroraank** [ErikGartner/dTree#80]
How i can show conditional custom paths styles for different spouses like example: green path for current spouse & red path for ex-spouse?

**Comment by ucay** [comment]
You can add your custom styles.
```js
/* Data object */
[{
    /* ... */
    class: "node spouse spouse_current",
    /* ... */
}]
```
```css
/* stylesheets */ 
.spouse{
    background-color: red;
}
.spouse_current{
    background-color: green;
}
```
